echo off

REM Requirements:
REM Install PDFtk, preferably using winget:
REM winget install PDFLabs.PDFtk.Free

REM To be used as a "Launcher" for PDF files opened with PDFGear. 
REM This executes pdftk to re-save the PDF and then open it with PDFGear's editor.
REM This is to avoid a potential issue where some PDF files generated by Microsoft PDF Editor
REM become un-openable on Adobe Acrobat when saved with PDFGear
REM You have to set this BAT file as the default program for .PDF files for this to work consistently
REM therefore, do NOT set PDFGear as your default PDF editor.

REM the arg1 is the full path to the input PDF file
set arg1=%1

REM Output the re-saved file to user's temp directory
REM delete the original file
REM then copy file from temp directory to working directory as if it's the original file
pdftk %1 cat output %TEMP%\file.pdf
del %1
copy %TEMP%\file.pdf %1
del %TEMP%\file.pdf

REM Open with PDFGear. 
start "" "C:\Program Files\PDFGear\pdfeditor.exe" %1
exit 0
